<a href="https://colab.research.google.com/github/cesarcabrerav-sudo/UEES-IA-Semana1-CabreraCesar/blob/main/01_Fundamentos_NumPy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Notebook 1: Fundamentos de NumPy y Pandas**

* Crear notebook: 01_Fundamentos_NumPy_Pandas.ipynb

* Ejercicios de manipulación de arrays con NumPy

* Análisis de datos con Pandas usando datasets de ejemplo

* Documentar cada celda con markdown explicativo



## **Ejercicios de manipulación de arrays con NumPy**

### **Ejercicio 1: Manipulacio de Arrays:**
Este código está diseñado para enseñarte las operaciones básicas y más comunes con arrays de NumPy en Python. Aquí te explico cada sección:

Importación de NumPy: Primero, se importa la librería NumPy, que es esencial para trabajar con arrays numéricos de manera eficiente en Python, asignándole el alias np.

* np.arange(10): Crea un array unidimensional (1D) con números enteros desde 0 hasta 9 (excluyendo el 10).

+ np.full((3, 3), True, dtype=bool): Genera un array bidimensional (2D) de 3x3, donde todos los elementos son booleanos (True).

* +np.random.rand(5, 5): Crea un array 2D de 5x5 con números aleatorios de punto flotante que están distribuidos uniformemente entre 0 y 1.

### **Ejercicio 2: Indexación y Selección:**

En esta sección, se explican diferentes maneras de acceder a elementos o subconjuntos de un array.

* arr_index[1]: Selecciona la segunda fila completa del array (la indexación en Python comienza en 0).

* arr_index[:, 2]: Selecciona la tercera columna completa. El : indica 'todas las filas'.

* arr_index[0:2, 3:5]: Extrae un sub-array que incluye las filas 0 y 1, y las columnas 3 y 4.

* arr_index[arr_index > 15]: Realiza una selección booleana, devolviendo un array 1D con todos los elementos del arr_index original que son mayores que 15.

### **Ejercicio 3: Remodelación (Reshape):**

Se muestra cómo cambiar la forma o las dimensiones de un array.

* arr_reshape.reshape(3, 4): Transforma un array 1D de 12 elementos en un array 2D con 3 filas y 4 columnas.

* arr_reshaped_2d.flatten(): Convierte el array 2D de nuevo a un array unidimensional (1D).

### **Ejercicio 4: Operaciones Aritméticas: Aquí se demuestran operaciones matemáticas básicas con arrays.**


* arr_a + arr_b: Suma elemento a elemento de dos arrays del mismo tamaño.
arr_a * 2: Multiplica cada elemento del arr_a por el escalar 2.
* np.dot(matrix_a, matrix_b): Realiza el producto punto (multiplicación de matrices) entre matrix_a y matrix_b. Es importante que las dimensiones de las matrices sean compatibles para esta operación (el número de columnas de la primera matriz debe ser igual al número de filas de la segunda).

Este código es un excelente punto de partida para entender cómo manipular datos eficientemente usando NumPy, lo cual es fundamental en la ciencia de datos y el aprendizaje automático.

In [ ]:
import numpy as np # Importa la librería NumPy, esencial para trabajar con arrays numéricos.

# Ejercicio 1: Crear arrays
print("--- Ejercicio 1: Creación de Arrays ---") # Imprime un encabezado para la sección.
# Salida: --- Ejercicio 1: Creación de Arrays ---

# a) Crea un array 1D con números del 0 al 9.
arr1 = np.arange(10) # Crea un array unidimensional (1D) con valores enteros de 0 a 9.
print("Array 1D (0-9):", arr1) # Imprime el array creado.
# Salida: Array 1D (0-9): [0 1 2 3 4 5 6 7 8 9]

# b) Crea un array 2D de 3x3 con valores booleanos (True/False).
arr2 = np.full((3, 3), True, dtype=bool) # Crea un array 2D de 3x3 donde todos los elementos son 'True'.
print("\nArray 2D 3x3 booleano:\n", arr2) # Imprime el array booleano.
# Salida:
# Array 2D 3x3 booleano:
#  [[ True  True  True]
#  [ True  True  True]
#  [ True  True  True]]

# c) Crea un array 2D de 5x5 con valores aleatorios entre 0 y 1.
arr3 = np.random.rand(5, 5) # Crea un array 2D de 5x5 con números aleatorios entre 0 y 1.
print("\nArray 2D 5x5 aleatorio (0-1):\n", arr3) # Imprime el array aleatorio.
# Salida: (El contenido variará debido a los números aleatorios)
# Array 2D 5x5 aleatorio (0-1):
#  [[0.06549087 0.0496809  0.43445105 0.85544363 0.03872789]
#  [0.14367088 0.743603   0.12245113 0.18635746 0.60182424]
#  [0.18186226 0.50672718 0.59084032 0.82800082 0.74890311]
#  [0.22927744 0.67751124 0.6245598  0.49919859 0.28779112]
#  [0.31446541 0.87763022 0.14830821 0.9606467  0.68027061]]

# Ejercicio 2: Indexación y selección
print("\n--- Ejercicio 2: Indexación y Selección ---") # Imprime un encabezado para la sección.
# Salida: --- Ejercicio 2: Indexación y Selección ---
arr_index = np.arange(25).reshape(5, 5) # Crea un array 2D de 5x5 con números del 0 al 24.
print("Array original para indexación:\n", arr_index) # Imprime el array para indexación.
# Salida:
# Array original para indexación:
#  [[ 0  1  2  3  4]
#  [ 5  6  7  8  9]
#  [10 11 12 13 14]
#  [15 16 17 18 19]
#  [20 21 22 23 24]]

# a) Selecciona la segunda fila del array.
row_2 = arr_index[1] # Selecciona la fila con índice 1 (la segunda fila).
print("\nSegunda fila:\n", row_2) # Imprime la segunda fila.
# Salida:
# Segunda fila:
#  [5 6 7 8 9]

# b) Selecciona la tercera columna del array.
col_3 = arr_index[:, 2] # Selecciona la columna con índice 2 (la tercera columna) de todas las filas.
print("\nTercera columna:\n", col_3) # Imprime la tercera columna.
# Salida:
# Tercera columna:
#  [ 2  7 12 17 22]

# c) Selecciona el sub-array formado por las filas 0 y 1, y las columnas 3 y 4.
sub_array = arr_index[0:2, 3:5] # Selecciona un sub-array de las filas 0 y 1, y las columnas 3 y 4.
print("\nSub-array (filas 0-1, cols 3-4):\n", sub_array) # Imprime el sub-array.
# Salida:
# Sub-array (filas 0-1, cols 3-4):
#  [[3 4]
#  [8 9]]

# d) Selecciona todos los elementos mayores que 15.
major_15 = arr_index[arr_index > 15] # Usa indexación booleana para seleccionar elementos mayores que 15.
print("\nElementos mayores que 15:\n", major_15) # Imprime los elementos seleccionados.
# Salida:
# Elementos mayores que 15:
#  [16 17 18 19 20 21 22 23 24]

# Ejercicio 3: Remodelación (Reshape)
print("\n--- Ejercicio 3: Remodelación (Reshape) ---") # Imprime un encabezado para la sección.
# Salida: --- Ejercicio 3: Remodelación (Reshape) ---
arr_reshape = np.arange(12) # Crea un array 1D con números del 0 al 11.
print("Array original para reshape:\n", arr_reshape) # Imprime el array original.
# Salida:
# Array original para reshape:
#  [ 0  1  2  3  4  5  6  7  8  9 10 11]

# a) Remodela el array de 1D a un array 2D de 3x4.
arr_reshaped_2d = arr_reshape.reshape(3, 4) # Remodela el array 1D a un array 2D de 3 filas y 4 columnas.
print("\nArray remodelado a 3x4:\n", arr_reshaped_2d) # Imprime el array remodelado.
# Salida:
# Array remodelado a 3x4:
#  [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# b) Remodela el array 2D anterior a un array 1D nuevamente.
arr_back_to_1d = arr_reshaped_2d.flatten() # Convierte el array 2D de nuevo a un array 1D.
print("\nArray de vuelta a 1D:\n", arr_back_to_1d) # Imprime el array 1D resultante.
# Salida:
# Array de vuelta a 1D:
#  [ 0  1  2  3  4  5  6  7  8  9 10 11]

# Ejercicio 4: Operaciones aritméticas
print("\n--- Ejercicio 4: Operaciones Aritméticas ---") # Imprime un encabezado para la sección.
# Salida: --- Ejercicio 4: Operaciones Aritméticas ---
arr_a = np.array([1, 2, 3, 4]) # Crea el primer array para operaciones.
arr_b = np.array([5, 6, 7, 8]) # Crea el segundo array para operaciones.
print("Array A:", arr_a) # Imprime el Array A.
# Salida: Array A: [1 2 3 4]
print("Array B:", arr_b) # Imprime el Array B.
# Salida: Array B: [5 6 7 8]

# a) Suma los dos arrays.
arr_sum = arr_a + arr_b # Realiza la suma elemento a elemento de los dos arrays.
print("\nSuma de A y B:", arr_sum) # Imprime el resultado de la suma.
# Salida: Suma de A y B: [ 6  8 10 12]

# b) Multiplica el array A por 2.
arr_mult = arr_a * 2 # Multiplica cada elemento del array A por 2.
print("\nArray A multiplicado por 2:", arr_mult) # Imprime el resultado de la multiplicación.
# Salida: Array A multiplicado por 2: [2 4 6 8]

# c) Realiza el producto punto (dot product) entre los arrays (si las dimensiones lo permiten).
# Para producto punto, los arrays deben ser 2D o usar np.dot con 1D arrays.
# Vamos a crear dos arrays 2D para este ejemplo.
matrix_a = np.array([[1, 2], [3, 4]]) # Crea la primera matriz para el producto punto.
matrix_b = np.array([[5, 6], [7, 8]]) # Crea la segunda matriz para el producto punto.
print("\nMatriz A para producto punto:\n", matrix_a) # Imprime la Matriz A.
# Salida:
# Matriz A para producto punto:
#  [[1 2]
#  [3 4]]
print("Matriz B para producto punto:\n", matrix_b) # Imprime la Matriz B.
# Salida:
# Matriz B para producto punto:
#  [[5 6]
#  [7 8]]

product_dot = np.dot(matrix_a, matrix_b) # Calcula el producto punto (multiplicación de matrices) de matrix_a y matrix_b.
print("\nProducto punto de A y B:\n", product_dot) # Imprime el resultado del producto punto.
# Salida:
# Producto punto de A y B:
#  [[19 22]
#  [43 50]]

--- Ejercicio 1: Creación de Arrays ---
Array 1D (0-9): [0 1 2 3 4 5 6 7 8 9]

Array 2D 3x3 booleano:
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]

Array 2D 5x5 aleatorio (0-1):
 [[0.83851538 0.06301834 0.78155645 0.49620008 0.09956213]
 [0.36578835 0.04432478 0.19986204 0.74676874 0.61699439]
 [0.10195624 0.2890706  0.87915314 0.76751083 0.86455233]
 [0.28859306 0.74734451 0.16789397 0.56073931 0.0042258 ]
 [0.4336034  0.85809372 0.99626202 0.10716072 0.67104962]]

--- Ejercicio 2: Indexación y Selección ---
Array original para indexación:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Segunda fila:
 [5 6 7 8 9]

Tercera columna:
 [ 2  7 12 17 22]

Sub-array (filas 0-1, cols 3-4):
 [[3 4]
 [8 9]]

Elementos mayores que 15:
 [16 17 18 19 20 21 22 23 24]

--- Ejercicio 3: Remodelación (Reshape) ---
Array original para reshape:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]

Array remodelado a 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 

## **Análisis de datos con Pandas usando datasets de ejemplo**

### **Explicación de los ejercicios realizados:**

Ejercicios de NumPy: Estos ejercicios te introducen a las bases de la librería NumPy, fundamental para la computación numérica en Python. Cubrimos:

Creación de Arrays: Aprendimos a generar arrays unidimensionales y bidimensionales con diferentes valores y formas.

Indexación y Selección: Vimos cómo acceder a elementos específicos, filas, columnas o subconjuntos de datos dentro de un array, e incluso cómo filtrar datos según condiciones.

Remodelación (Reshape): Practicamos cómo cambiar la estructura de un array, por ejemplo, de una dimensión a dos, y viceversa.

Operaciones Aritméticas: Realizamos operaciones matemáticas básicas como sumas elemento a elemento, multiplicaciones por escalares y el importante producto punto entre matrices.

Análisis de Datos con Pandas: Esta sección se enfocó en la librería Pandas, esencial para el análisis y manipulación de datos tabulares. Los ejercicios incluyeron:

**Creación de un DataFrame:**
Creamos una estructura de datos tipo tabla (DataFrame) a partir de un diccionario.

**Inspección Básica:** Utilizamos funciones como head(), info() y describe() para obtener una visión rápida de la estructura, tipos de datos y estadísticas resumidas de nuestro DataFrame.

**Selección de Datos:** Aprendimos a seleccionar columnas específicas o filas utilizando sus índices o nombres.

**Filtrado de Datos:** Filtramos el DataFrame para obtener solo las filas que cumplen ciertas condiciones.

**Adición de Nuevas Columnas:** Calculamos y añadimos una nueva columna basada en los datos existentes.

**Agregación y Agrupamiento (groupby):** Agrupamos los datos por categorías para realizar cálculos agregados, como la suma total o el precio promedio por categoría.

In [ ]:
import pandas as pd # Importa la librería Pandas para análisis de datos, con el alias 'pd'.

# Ejercicio 1: Creación de un DataFrame
print("--- Ejercicio 1: Creación de un DataFrame ---") # Imprime un encabezado para la sección.
# Creamos un DataFrame de ejemplo a partir de un diccionario. Un DataFrame es como una tabla de Excel.
data = {
    'Producto': ['Laptop', 'Mouse', 'Teclado', 'Monitor', 'Webcam'],
    'Precio': [1200, 25, 75, 300, 50],
    'Cantidad': [10, 50, 30, 5, 20],
    'Categoria': ['Electrónica', 'Accesorios', 'Accesorios', 'Electrónica', 'Accesorios']
}
df = pd.DataFrame(data) # Crea el DataFrame utilizando el diccionario 'data'.
print("DataFrame inicial:\n", df) # Muestra el DataFrame completo.
# Salida:
# DataFrame inicial:
#     Producto  Precio  Cantidad    Categoria
# 0     Laptop    1200        10  Electrónica
# 1      Mouse      25        50   Accesorios
# 2    Teclado      75        30   Accesorios
# 3    Monitor     300         5  Electrónica
# 4     Webcam      50        20   Accesorios

# Ejercicio 2: Inspección básica del DataFrame
print("\n--- Ejercicio 2: Inspección básica del DataFrame ---") # Imprime un encabezado para la sección.
print("Primeras 3 filas (df.head(3)):\n", df.head(3)) # Muestra las primeras N filas del DataFrame (por defecto 5, aquí 3).
# Salida:
# Primeras 3 filas (df.head(3)):
#     Producto  Precio  Cantidad    Categoria
# 0     Laptop    1200        10  Electrónica
# 1      Mouse      25        50   Accesorios
# 2    Teclado      75        30   Accesorios

print("\nInformación del DataFrame (df.info()):") # Proporciona un resumen conciso del DataFrame (columnas, tipos de datos, valores no nulos).
df.info()
# Salida:
# Información del DataFrame (df.info()):
# <class 'pandas.core.frame.DataFrame'>
# RangeIndex: 5 entries, 0 to 4
# Data columns (total 4 columns):
#  #   Column     Non-Null Count  Dtype
# ---  ------     --------------  -----
#  0   Producto   5 non-null      object
#  1   Precio     5 non-null      int64
#  2   Cantidad   5 non-null      int64
#  3   Categoria  5 non-null      object
# dtypes: int64(2), object(2)
# memory usage: 288.0+ bytes

print("\nEstadísticas descriptivas (df.describe()):\n", df.describe()) # Genera estadísticas descriptivas (conteo, media, std, min, max, cuartiles) de las columnas numéricas.
# Salida:
# Estadísticas descriptivas (df.describe()):
#           Precio   Cantidad
# count    5.000000   5.000000
# mean   330.000000  23.000000
# std    494.398638  17.755008
# min     25.000000   5.000000
# 25%     50.000000  10.000000
# 50%     75.000000  20.000000
# 75%    300.000000  30.000000
# max   1200.000000  50.000000

# Ejercicio 3: Selección de datos
print("\n--- Ejercicio 3: Selección de datos ---") # Imprime un encabezado para la sección.
print("Columna 'Producto':\n", df['Producto']) # Selecciona una única columna por su nombre.
# Salida:
# Columna 'Producto':
# 0     Laptop
# 1      Mouse
# 2    Teclado
# 3    Monitor
# 4     Webcam
# Name: Producto, dtype: object

print("\nColumnas 'Producto' y 'Precio':\n", df[['Producto', 'Precio']]) # Selecciona múltiples columnas pasando una lista de nombres.
# Salida:
# Columnas 'Producto' y 'Precio':
#     Producto  Precio
# 0     Laptop    1200
# 1      Mouse      25
# 2    Teclado      75
# 3    Monitor     300
# 4     Webcam      50

print("\nFila en índice 1 (iloc):\n", df.iloc[1]) # Selecciona una fila por su posición numérica (índice).
# Salida:
# Fila en índice 1 (iloc):
# Producto        Mouse
# Precio             25
# Cantidad           50
# Categoria  Accesorios
# Name: 1, dtype: object

# Ejercicio 4: Filtrado de datos
print("\n--- Ejercicio 4: Filtrado de datos ---") # Imprime un encabezado para la sección.
# Filtramos productos con precio mayor a 100.
productos_caros = df[df['Precio'] > 100] # Selecciona filas donde la condición 'Precio > 100' es verdadera.
print("Productos con Precio > 100:\n", productos_caros)
# Salida:
# Productos con Precio > 100:
#   Producto  Precio  Cantidad    Categoria
# 0   Laptop    1200        10  Electrónica
# 3  Monitor     300         5  Electrónica

# Ejercicio 5: Agregar una nueva columna
print("\n--- Ejercicio 5: Agregar una nueva columna ---") # Imprime un encabezado para la sección.
df['ValorTotal'] = df['Precio'] * df['Cantidad'] # Crea una nueva columna 'ValorTotal' calculada a partir de otras columnas.
print("DataFrame con 'ValorTotal':\n", df)
# Salida:
# DataFrame con 'ValorTotal':
#     Producto  Precio  Cantidad    Categoria  ValorTotal
# 0     Laptop    1200        10  Electrónica       12000
# 1      Mouse      25        50   Accesorios        1250
# 2    Teclado      75        30   Accesorios        2250
# 3    Monitor     300         5  Electrónica        1500
# 4     Webcam      50        20   Accesorios        1000

# Ejercicio 6: Agregación y agrupamiento (groupby)
print("\n--- Ejercicio 6: Agregación y agrupamiento (groupby) ---") # Imprime un encabezado para la sección.
# Calculamos el valor total por categoría.
valor_por_categoria = df.groupby('Categoria')['ValorTotal'].sum() # Agrupa el DataFrame por 'Categoria' y suma los 'ValorTotal' de cada grupo.
print("Valor total por Categoría:\n", valor_por_categoria)
# Salida:
# Valor total por Categoría:
# Categoria
# Accesorios      4500
# Electrónica    13500
# Name: ValorTotal, dtype: int64

# Calculamos el precio promedio por categoría.
precio_promedio_categoria = df.groupby('Categoria')['Precio'].mean() # Agrupa por 'Categoria' y calcula el promedio de 'Precio' para cada grupo.
print("\nPrecio promedio por Categoría:\n", precio_promedio_categoria)
# Salida:
# Precio promedio por Categoría:
# Categoria
# Accesorios     50.0
# Electrónica    750.0
# Name: Precio, dtype: float64

--- Ejercicio 1: Creación de un DataFrame ---
DataFrame inicial:
   Producto  Precio  Cantidad    Categoria
0   Laptop    1200        10  Electrónica
1    Mouse      25        50   Accesorios
2  Teclado      75        30   Accesorios
3  Monitor     300         5  Electrónica
4   Webcam      50        20   Accesorios

--- Ejercicio 2: Inspección básica del DataFrame ---
Primeras 3 filas (df.head(3)):
   Producto  Precio  Cantidad    Categoria
0   Laptop    1200        10  Electrónica
1    Mouse      25        50   Accesorios
2  Teclado      75        30   Accesorios

Información del DataFrame (df.info()):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Producto   5 non-null      object
 1   Precio     5 non-null      int64 
 2   Cantidad   5 non-null      int64 
 3   Categoria  5 non-null      object
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
# En cada notebook, añadir celda final para guardar en GitHub
# 1. Conectar Colab con GitHub
from google.colab import auth
auth.authenticate_user()

# 2. Configurar Git
# Asegúrate de reemplazar "tu.email@estudiantes.uees.edu.ec" y "Tu Nombre" con tus credenciales de Git.
!git config --global user.email "cesar.cabrerav@uees.edu.ec"
!git config --global user.name "cesarcabrerav-sudo"

# 3. Clonar tu repositorio
# IMPORTANTE: Necesitarás un Personal Access Token (PAT) de GitHub para clonar y hacer push.
# Si tu repositorio es privado o si usas autenticación basada en token, GitHub requiere un PAT.
# Reemplaza 'ghp_YOUR_PERSONAL_ACCESS_TOKEN' con tu token real.
# La URL debe tener el formato: https://ghp_YOUR_PERSONAL_ACCESS_TOKEN@github.com/tu-usuario/nombre-del-repositorio.git
# Genera tu PAT aquí: https://docs.github.com/es/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
!git clone https://github.com/cesarcabrerav-sudo/UEES-IA-Semana1-CabreraCesar.git
%cd UEES-IA-Semana1-CabreraCesar

# 4. Guardar el notebook actual y copiarlo al repositorio
# El error 'No such file or directory' ocurre porque el archivo
# '01_Fundamentos_NumPy_Pandas.ipynb' no existe en /content/ directamente.
# Para guardar este notebook (el que estás ejecutando) con un nombre específico
# y poder copiarlo al repositorio, la forma más sencilla es usar Google Drive como intermediario.

# a) Montar Google Drive
# Esto te permitirá acceder a los archivos guardados en tu Google Drive.
from google.colab import drive
drive.mount('/content/drive')

# b) Asegúrate de que este notebook esté guardado en tu Google Drive
# con el nombre `01_Fundamentos_NumPy_Pandas.ipynb`
# (por ejemplo, en 'Mi Unidad/Colab Notebooks/01_Fundamentos_NumPy_Pandas.ipynb').
# Puedes hacerlo manualmente desde 'Archivo > Guardar una copia en Drive' en Colab.

# c) Copiar el notebook desde Google Drive al repositorio clonado.
# Ajusta la ruta si tu notebook está en una subcarpeta diferente dentro de 'Mi Unidad'.
!cp "/content/drive/My Drive/Colab Notebooks/01_Fundamentos_NumPy_Pandas.ipynb" "./02_Laboratorio/notebooks/"

# 5. Hacer commit y push
!git add .
!git commit -m "Añadir notebook de fundamentos"
!git push origin main

Cloning into 'UEES-IA-Semana1-CabreraCesar'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (3/3), done.
/content/UEES-IA-Semana1-CabreraCesar
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
cp: cannot create regular file './02_Laboratorio/notebooks/': No such file or directory
On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
fatal: could not read Username for 'https://github.com': No such device or address
